site_name: 832考研笔记
theme:
  name: material

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - 首页: index.md
  - 1.重力勘探(10'): 重力勘探.md
  - 2.磁法勘探(10'): 磁法勘探.md
  - 3.地震勘探(20'): 地震勘探.md
  - 4.电(磁)法勘探(30'): 电(磁)法勘探.md
